server:
  port: 5003

spring:
  application:
    name: PRODUCT-SERVICE
  #  security:
  #    oauth2:
  #      resourceserver:
  #        jwt:
  #          issuer-uri: "http://localhost:8080/auth/realms/hc-intershop-realm"


  datasource:
    driver-class-name: org.postgresql.Driver
    username: internshop
    password: internshop_passw0rd
    url: jdbc:postgresql://internshop.cmalzj6opuhz.eu-central-1.rds.amazonaws.com:5432/hc_intern_shop
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgresql
  sql:
    init:
      platform: postgres
      mode: always
      continue-on-error: true

  zipkin:
    base-url: http://127.0.0.1:9411/

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://af799cbd9e05549758b7c3059ec8616e-745050297.eu-west-2.elb.amazonaws.com/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}

management:
  endpoints:
    web:
      exposure:
        include: "*"
